# Generated by Django 6.0.6 on 2026-06-12 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sleep_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wake_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_hours',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(16.0)]),
        ),
    ]
